version: "3.8"

services:
  web:
    build: '.'
    ports:
      - "4000:4000"
    volumes:
      - .:/opt/app
    environment:
      PG_URL: postgres:postgres@db
      LIVE_ADMIN_DEV: 'true'
    depends_on:
      - db
    command: mix dev
  db:
    environment:
      POSTGRES_DB: phx_admin_dev
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    image: 'postgres:13-alpine'
    volumes:
      - './dev/initdb:/docker-entrypoint-initdb.d'
